[package]
name = "operation"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate_type = ["proc-macro"]

[dependencies]
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
proc-macro2 = "1.0"
