
[package]
name = "calculator-app-interpreter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
spfunc = "0.1.0"
unicode-width = "0.1.11"
operation = { path = "operation" }
